name: visionguard
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  curved_navigation_bar: ^1.0.6
  supabase_flutter: ^2.8.4
  flutter_dotenv: ^5.2.1
  provider: ^6.1.4
  audioplayers: ^5.2.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.7

  latlong2: ^0.9.1
  flutter_map: ^8.1.1
  flutter_map_location_marker: ^10.1.0
  location: ^8.0.0
  http: ^1.3.0
  flutter_polyline_points: ^2.1.0

  cupertino_icons: ^1.0.8
  agora_rtc_engine: ^6.2.0
  permission_handler: ^12.0.0+1
  flutter_tts: ^3.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
 
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  image_path: "images/loogoo.jpg"
  android: true
  ios: true



flutter:
  uses-material-design: true

  assets:
    - .env
    - images/
    - assets/sounds/ringtone.mp3
    - assets/avatars/
